"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WindowsTest = exports.SelectTest = exports.InputTest = exports.Header = exports.HomePage = void 0;
const home_po_1 = require("./home.po");
Object.defineProperty(exports, "HomePage", { enumerable: true, get: function () { return home_po_1.HomePage; } });
const header_po_1 = require("./header.po");
Object.defineProperty(exports, "Header", { enumerable: true, get: function () { return header_po_1.Header; } });
const inputTest_po_1 = require("./inputTest.po");
Object.defineProperty(exports, "InputTest", { enumerable: true, get: function () { return inputTest_po_1.InputTest; } });
const selectTest_po_1 = require("./selectTest.po");
Object.defineProperty(exports, "SelectTest", { enumerable: true, get: function () { return selectTest_po_1.SelectTest; } });
const windowsTest_po_1 = require("./windowsTest.po");
Object.defineProperty(exports, "WindowsTest", { enumerable: true, get: function () { return windowsTest_po_1.WindowsTest; } });
